#!/bin/bash

# Bugs: 1. output all xtrace to file
#       2. needs a process lock on kill loop

## Notes
###   Online Git Pro book:
###     https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository

# Regular users only
if [[ "${UID}" == 0 ]]; then
  printf '\n\t Must be a regular user and use sudo. \n\n'
  exit 1
else
  sudo -v \
    || exit 1
fi

# Vars
declare -n nL=LINENO

# Network & time
if ! sudo ping -c 1 -W 15 8.8.8.8; then
  printf '\n\tAttempting to connect...\n\n'
  sudo systemctl start NetworkManager.service
  wait -f
  sleep 15
  if ! sudo ping -c 1 -W 15 8.8.8.8; then 
    printf '\n\tGiving up; Exiting.\n\n'
    exit "${nL}"
  else
    printf '\n\tSuccess!\n\n'
  fi
fi
sudo timedatectl set-local-rtc 0
sudo timedatectl set-timezone America/Vancouver
sudo systemctl start chronyd.service
sudo chronyc makestep

# Bash
## .bashrc
umask 071
bashrc_str='EDITOR=/usr/bin/vim; BROWSER=/usr/bin/firefox;'

files=(/root/.bashrc /home/*/.bashrc)
for f in "${files[@]}"; do

  if ! sudo grep -q -- "${bashrc_str}" "${f}"; then
    sudo cp -a -- "${f}" "${f}~"
    echo "${bashrc_str}" \
      | sudo tee -a -- "${f}" > /dev/null
  fi
done
unset files f

# Vim
umask 177
tmpf="$(mktemp)"
cat << EOF > "${tmpf}"
" per google:
set number

" per https://stackoverflow.com/questions/234564/tab-key-4-spaces-and-auto-indent-after-curly-braces-in-vim
filetype plugin indent on
" show existing tab with 2 spaces width
set tabstop=2
" when indenting with '>', use 2 spaces width
set shiftwidth=2
" On pressing tab, insert 2 spaces
set expandtab
EOF
# shellcheck disable=SC2024
sudo tee /root/.vimrc < "${tmpf}" > /dev/null
rm -f -- "${tmpf}"
unset tmpf

## Copy root-user files to $USER
sudo rsync -ca /root/.vimrc "/home/${USER}"
sudo chown "${UID}:${UID}" "/home/${USER}/.vimrc"
chmod 0400 "/home/${USER}/.vimrc"

# Dnf
sudo dnf -y install \
  angband \
  git gh \
  ShellCheck kcov shfmt patch strace ltrace \
  info binutils parallel procmail \
  lynx libreoffice-calc chromium mozilla-noscript mozilla-privacy-badger \
    mozilla-https-everywhere \
  debian-keyring \
  procps-ng \
  git-fame # 🙄 #memstomp bpftrace gdb valgrind
sudo dnf -y upgrade bash
sudo dnf -y --security upgrade

  # <>
  set -x


# Any processes that may need to be restarted

# let the previous DNF processes finish
pidwait dnf 

# Get a list of any such PIDs
declare -ax a_pids
function _get_pids(){
  mapfile -t a_pids < <(
    sudo dnf needs-restarting |& 
    awk '{ print $1 }' | 
      grep -E ^'[0-9]*'$
  )
}; declare -fxt _get_pids
_get_pids

# if any PIDs were found...
if [[ -n "${a_pids[*]:0:8}" ]]; then 
  n="${#a_pids[@]}"
  
  # ...if there are any PIDs other than PID 1...
  if [[ "${a_pids[*]:0:8}" -ne 1 ]]; then
    
    # Print some info & wait for it to be read
    printf '\n\t PID-s, count: %d\n\n' "${n}"
    sleep 1

    #printf '\t Backgrounding and disowning -kill- loops.\n\n'
    #sleep 3
    #{
      # for each signal and for each PID...
      for s in HUP USR1 TERM; do
        for p in "${!a_pids[@]}"; do
          
          # (for readability)
          q="${a_pids[p]}"
          sleep 1

          printf '\t[script:] + sudo kill -s %s %d\n' "${s}" "${q}"
          set -

          if pgrep "$q"
            
            sudo kill -s "${s}" "${q}" > /dev/null 2>&1; then
            printf '\t[script:] + kill succeeded; forgetting PID\n' 
            unset 'a_pids[p]'
          else
            printf '\t[script:] + kill failed\n' 
          fi
        done;
      done;
      printf '\n\n\tScript complete. [Press ENTER.]\n\n'
    #} #&
    #disown
  elif [[ "${a_pids[*]}" -eq 1 ]]; then 
    printf '\n\t The remaining "needs-restarting" process cannot be '
    printf 'restarted \n\t without rebooting the machine.\n'
    printf '\n\t %s \n\n' "${a_pids[@]}"
    printf '\n\n\tScript complete.\n\n'
  fi
fi;

_get_pids

if [[ -n "${a_pids[*]:0:8}" ]]; then
  for s in HUP USR1 USR2 TERM; do

    for p in "${a_pids[@]}"; do 
      echo "$p"; 
      set -x; 
      kill -s "$s" "$p"; 
      echo exit, kill: $?; 
      set -; 
      sleep 1; 
    done
  
    _get_pids
    
    if [[ -n "${a_pids[*]:0:8}" ]]; then
      continue
    else
      break
    fi
      
  done
fi

if ! ping -4qc1 8.8.8.8 2> /dev/null >&2; then 
  sudo systemctl restart NetworkManager.service
fi

exit 00

