#!/bin/bash


[[ "$UID" == 0 ]] && {
  echo Must be a regular user.
  exit 1
}
umask 077


if [[ ! -d ~/MYPROJECT ]]; then 
  mkdir -p ~/MYPROJECT ||
    exit "$LINENO"
fi

# Note: in order to clone into any repo, and keep them all separate, 
# `cd` is required
cd ~/MYPROJECT || {
  echo cd failed
  exit 1
}

# Log in & clone repo
gh auth logout

gh auth login ||
  exit "$LINENO"

if [[ ! -d ~/MYPROJECT/scf ]]; then
  git clone -o github https://github.com/wileyhy/scf ||
    exit "$LINENO"
fi

printf '\n\t Now run this command: \n'
printf '\n\t cd ./MYPROJECT/scf; git status \n\n'


