#!/bin/bash
# set-up-git_sudo-sh

## Notes
###   Online Git Pro book:
###     https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository

# Regular users only
if [[ "${UID}" == 0 ]]; then
  printf '\n\t Must be a regular user and use sudo. \n\n'
  exit 1
else
  sudo -v \
    || exit 1
fi

# Network & time
if ! sudo ping -c 1 -W 15 8.8.8.8; then
  sudo systemctl start NetworkManager.service
  wait -f
  sleep 15
  sudo ping -c 1 -W 15 8.8.8.8 \
    || exit "${LINENO}"
fi

# BASH
## .bashrc
umask 071
bashrc_str='EDITOR=/usr/bin/vim; BROWSER=/usr/bin/firefox'

files=(/root/.bashrc /home/*/.bashrc)
for f in "${files[@]}"; do

  if ! sudo grep -q "${bashrc_str}" "${f}"; then
    sudo cp -a "${f}" "${f}~"
    echo "${bashrc_str}" \
      | sudo tee -a "${f}" >/dev/null
  fi
done

# VIM
umask 177
tmpf="$(mktemp)"
cat <<EOF >"${tmpf}"
" per google:
set number

" per https://stackoverflow.com/questions/234564/tab-key-4-spaces-and-auto-indent-after-curly-braces-in-vim
filetype plugin indent on
" show existing tab with 2 spaces width
set tabstop=2
" when indenting with '>', use 2 spaces width
set shiftwidth=2
" On pressing tab, insert 2 spaces
set expandtab
EOF
sudo tee /root/.vimrc < "${tmpf}" >/dev/null
rm -f "${tmpf}"

## Copy root-user files to liveuser
sudo rsync -ca /root/.vimrc /home/liveuser
sudo chown 1000:1000 /home/liveuser/.vimrc
chmod 0400 /home/liveuser/.vimrc

# GIT
sudo git config --system user.name 'Wiley Young'
sudo git config --system user.email '84648683+wileyhy@users.noreply.github.com'
sudo git config --system core.editor 'vim'
sudo git config --system core.pager '/usr/bin/less'
sudo git config --system help.autocorrect '300'
sudo git config --system init.defaultBranch 'main'

## re Gnupg
sudo git config --system --unset gpg.format
sudo git config --system commit.gpgsign 'true'
sudo git config --system gpg.program 'gpg2'
sudo git config --system user.signingkey 'E287D0CF528591CE'

## Console colors
## git ui colors: normal black red green yellow blue magenta cyan white
## git ui attributes: bold dim ul (underline blink reverse
sudo git config --system color.diff 'always'
sudo git config --system color.diff.meta 'blue black bold'
sudo git config --system color.interactive 'always'
sudo git config --system color.status 'always'
sudo git config --system color.ui 'true'
sudo git config --system color.ui 'auto'

## .gitmessage and .gitignore
gitmesg=/etc/.gitmessage_system
gitignr=/etc/.gitignore_system

## (message)
tmpf="$(mktemp)"
cat <<EOF >"${tmpf}"
Subject line (try to keep under 50 characters)

Multi-line description of commit,
feel free to be detailed.

[Ticket: X]
EOF
sudo tee "${gitmesg}" <<<"${tmpf}" >/dev/null
rm -f "${tmpf}"

## (ignore)
tmpf="$(mktemp)"
cat <<EOF >"${tmpf}"
*~
.*.swp
.DS_Store
EOF
sudo tee "${gitignr}" <<<"${tmpf}" >/dev/null
rm -f "${tmpf}"

sudo git config --system commit.template "${gitmesg}"
sudo git config --system core.excludesfile "${gitignr}"

## Permissions
files=(/etc/git* /etc/.git*)
for f in "${files[@]}"; do
  sudo chmod 0604 "${f}"
done

## Copy root-user files to liveuser
for f in "${gitmesg}" "${gitignr}"; do
  sudo rsync -ca "${f}" /home/liveuser
  sudo chown 1000:1000 "/home/liveuser/${f##*/}"
  chmod 0400 "/home/liveuser/${f##*/}"
done

# BUG: Dup btw files array and for loop

## Rename files
files=(/home/*/.git*_system)
for f in /home/*/.git*_system; do
  mv -f "${f}" "${f%_system}"
done

## make and change into directories
umask 077

if [[ ! -d ~/MYPROJECT ]]; then
  mkdir -p ~/MYPROJECT \
    || exit "${LINENO}"
fi

### Note: in order to clone into any repo, and keep multiple repos
### separate, `cd` is required
cd ~/MYPROJECT \
  || exit "${LINENO}"

# GH
gh config set editor vim
gh config set browser firefox
gh config set pager less
gh config set git_protocol ssh --host github.com

# Log in
if ! gh auth status 2>/dev/null; then
  gh auth login --git-protocol ssh --hostname github.com --scopes admin:public_key,read:gpg_key --web \
    || exit "${LINENO}"
fi

# Clone repo
if [[ ! -d ./scrfi ]] \
  || [[ ! -f ./scrfi/README.md ]]; then
  git clone -o github https://github.com/wileyhy/scrfi \
    || exit "${LINENO}"
fi

## Use GitHub CLI as a credential helper
gh auth setup-git --hostname github.com

## Get SSH key
#gh auth refresh --hostname github.com --scopes admin:public_key,read:gpg_key
gh ssh-key list

## Get GPG key
#gh auth refresh --hostname github.com --scopes read:gpg_key
gh gpg-key list

## Review auth
gh auth status --show-token

# SSH
sudo chown 1000:1000 ~/.ssh \
  || "${LINENO}"
sudo chmod -R 700 ~/.ssh

if [[ -e ~/.ssh/config ]]; then
  if ! grep -q 'ForwardAgent yes' ~/.ssh/config; then
    cat <<EOF >~/.ssh/config
    Host github.com
      ForwardAgent yes
EOF
  fi
fi

[[ -e /etc/ssh_config ]] \
  && exit "${LINENO}"

### Bug? not necc to restart ssh-agent if both of these vars exist?
# shellcheck disable=SC2154
declare -p SSH_AUTH_SOCK SSH_AGENT_PID

ps_o="$(ps aux)"
awk_o="$(awk '$0 ~ /ssh-agent/ && $0 !~ /startx/ { print $2 }' \
  <<<"${ps_o:?}")"
if [[ -n "${awk_o}" ]]; then 
  mapfile -t ssh_agent_pids <<<"${awk_o:?}"
fi
unset ps_o awk_o

if [[ "${#ssh_agent_pids[@]}" -gt 0 ]]; then
  case "${#ssh_agent_pids[@]}" in
    0) : ;;
    1) if [[ -v SSH_AGENT_PID ]]; then
      ssh-agent -k
    else
      kill "${ssh_agent_pids[*]}"
    fi ;;
    *) for p in "${ssh_agent_pids[@]}"; do
      kill "${p}"
    done ;;
  esac
fi

ssh_agent_o="$(ssh-agent -s)"
eval "${ssh_agent_o}"
unset ssh_agent_o

ssh-add ~/.ssh/id_ed25519
ssh-add -L
ssh -T git@github.com

# GPG
sudo chown 1000:1000 ~/.gnupg \
  || exit "${LINENO}"
sudo chmod -R 700 ~/.gnupg

### shellcheck disable=SC2009
ps_o="$(ps aux)"
if grep -qE '[g]pg-a.*daemon' <<<"${ps_o}"; then
  gpgconf --kill gpg-agent
fi
unset ps_o

gpg-connect-agent /bye

GPG_TTY=$(tty)
export GPG_TTY

# Remind user of commands for the interactive shell
printf '\n\t Now run this command: \n'
printf '\n\t cd /home/liveuser/MYPROJECT/scrfi; git status \n\n'
